name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
        java-package: jdk
        architecture: x64
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true
    - name: Build
      run: mvn -DskipTests=true assembly:assembly -DdescriptorId=jar-with-dependencies
    - name: Run tests
      run: mvn test
    - name: Create package
      run: mvn package -DskipTests=true
    - uses: actions/upload-artifact@v2
      with:
        path: target/components/packages/*.zip